# Generated by Django 2.1.2 on 2018-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
