# Generated by Django 2.1.2 on 2019-02-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='side_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
